import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='Chemistry',
                  teacher_name='Mr. Hockenos',
                  resource_name='www.rsc.org',
                  resource_url='www.rsc.org/learn-chemistry'),
    course.Course(period=3,
                  name='US History',
                  teacher_name='Ms.Chin',
                  resource_name='besthistorysites.net',
                  resource_url='besthistorysites.net/american-history'),
    course.Course(period=4,
                  name='English 2 CP',
                  teacher_name='Ms.Moss',
                  resource_name='Spark Notes',
                  resource_url='http://www.sparknotes.com/'),
    course.Course(period=5,
                  name='Geometry',
                  teacher_name='Ms.Sun',
                  resource_name='Khan Academy',
                  resource_url='https://www.khanacademy.org/math/geometry'),
    course.Course(period=6,
                  name='Advanced Physical Education',
                  teacher_name='Schaukowitch',
                  resource_name='Advanced PE',
                  resource_url='https://sparkpe.org/physical-education-resources/'),
]
